"""
stream_to_r2.py
===============
Stream a fal.ai video URL directly into Cloudflare R2 via FFmpeg + Pre-signed PUT.
No temporary files are written to local disk.

Usage:
    python stream_to_r2.py

Requirements:
    pip install boto3
    ffmpeg must be installed and accessible in PATH

How it works:
    1. Generate a time-limited pre-signed PUT URL for the target R2 object key.
    2. Invoke FFmpeg as a subprocess:
         - Input  : fal.ai CDN URL (downloaded over HTTPS by FFmpeg)
         - Process: stream-copy without re-encoding (-c copy)
         - Output : fragmented MP4 piped via HTTP PUT to the pre-signed R2 URL
    3. FFmpeg stderr is printed in real time for progress/debugging.
    4. On non-zero exit code an exception is raised.

Why fragmented MP4 (-movflags frag_keyframe+empty_moov)?
    Standard MP4 needs the 'moov' atom (index) at the end, which requires
    knowing the total file size before writing.  Fragmented MP4 interleaves
    metadata with each chunk, enabling true streaming to a PUT endpoint.
"""

import subprocess
import sys
import boto3
from botocore.exceptions import BotoCoreError, ClientError

# ─────────────────────────────────────────────────────────────────────────────
# ✏️  Replace these placeholders with your actual credentials
# ─────────────────────────────────────────────────────────────────────────────

R2_ACCOUNT_ID      = "YOUR_CLOUDFLARE_ACCOUNT_ID"
R2_ACCESS_KEY_ID   = "YOUR_R2_ACCESS_KEY_ID"
R2_SECRET_ACCESS_KEY = "YOUR_R2_SECRET_ACCESS_KEY"
R2_BUCKET_NAME     = "YOUR_R2_BUCKET_NAME"

# Target object key inside the bucket (path + filename)
R2_OBJECT_KEY      = "videos/reels/test_output.mp4"

# fal.ai video URL to stream (replace with your actual URL)
FAL_VIDEO_URL      = "https://v3b.fal.media/files/b/YOUR_HASH/YOUR_FILE.mp4"

# Pre-signed URL validity in seconds (1 hour default — enough for any FFmpeg run)
PRESIGNED_EXPIRY   = 3600

# ─────────────────────────────────────────────────────────────────────────────


def generate_presigned_put_url(
    account_id: str,
    access_key: str,
    secret_key: str,
    bucket: str,
    key: str,
    expiry: int = PRESIGNED_EXPIRY,
) -> str:
    """
    Generate a time-limited pre-signed URL for an S3/R2 PutObject operation.

    The URL allows any bearer to PUT an object to the specified key without
    requiring AWS credentials on the client (FFmpeg in our case).

    Args:
        account_id: Cloudflare account ID (used to build the R2 endpoint URL)
        access_key: R2 access key ID
        secret_key: R2 secret access key
        bucket:     Bucket name
        key:        Destination object key inside the bucket
        expiry:     URL validity in seconds (default 3600)

    Returns:
        HTTPS pre-signed URL string

    Raises:
        RuntimeError: If boto3 cannot connect or sign the request
    """
    endpoint = f"https://{account_id}.r2.cloudflarestorage.com"

    try:
        s3 = boto3.client(
            "s3",
            endpoint_url=endpoint,
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
            region_name="auto",
        )
        url = s3.generate_presigned_url(
            "put_object",
            Params={
                "Bucket": bucket,
                "Key": key,
                "ContentType": "video/mp4",
            },
            ExpiresIn=expiry,
            HttpMethod="PUT",
        )
        print(f"[R2] Pre-signed PUT URL generated (expires in {expiry}s)")
        return url

    except (BotoCoreError, ClientError) as exc:
        raise RuntimeError(f"Failed to generate pre-signed URL: {exc}") from exc


def stream_fal_to_r2(fal_url: str, presigned_url: str) -> None:
    """
    Stream a fal.ai video URL into R2 via FFmpeg without saving to disk.

    FFmpeg pipeline:
        Input  → fal.ai HTTPS URL  (FFmpeg fetches over the network)
        Codec  → stream-copy (-c copy, no re-encoding, lossless)
        Format → fragmented MP4 (-f mp4 -movflags frag_keyframe+empty_moov)
        Output → HTTP PUT to pre-signed R2 URL (-method PUT)

    Args:
        fal_url:       Public CDN URL of the source video (fal.media)
        presigned_url: Pre-signed R2 PUT URL generated by generate_presigned_put_url()

    Raises:
        RuntimeError: If FFmpeg exits with a non-zero return code
    """
    cmd = [
        "ffmpeg",
        # Allow HTTPS input
        "-protocol_whitelist", "file,http,https,tcp,tls,crypto",
        # Input: fal.ai CDN URL (no temp file)
        "-i", fal_url,
        # Stream copy: preserve original codec, no quality loss, fast
        "-c", "copy",
        # Fragmented MP4: required for streaming to HTTP PUT without known file size
        "-movflags", "frag_keyframe+empty_moov",
        # Output format
        "-f", "mp4",
        # Tell FFmpeg to use HTTP PUT instead of default POST
        "-method", "PUT",
        # Content-Type header so R2 stores the correct MIME type
        "-headers", "Content-Type: video/mp4\r\n",
        # Output destination: pre-signed R2 URL (no quotes needed in list form)
        presigned_url,
    ]

    print(f"\n[FFmpeg] Starting stream: {fal_url}")
    print(f"[FFmpeg] → R2 destination: {presigned_url[:80]}...\n")

    # Run FFmpeg — print stderr in real time for progress visibility
    proc = subprocess.Popen(
        cmd,
        stderr=subprocess.PIPE,
        stdout=subprocess.DEVNULL,
        text=True,
        encoding="utf-8",
        errors="replace",
    )

    for line in proc.stderr:
        print(line, end="", flush=True)

    proc.wait()

    if proc.returncode != 0:
        raise RuntimeError(
            f"FFmpeg exited with non-zero code {proc.returncode}. "
            "Check stderr output above for details."
        )

    print(f"\n[R2] Upload complete → {R2_BUCKET_NAME}/{R2_OBJECT_KEY}")


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=== fal.ai → Cloudflare R2 Direct Streaming (no temp files) ===\n")

    try:
        # Step 1: Generate pre-signed PUT URL
        put_url = generate_presigned_put_url(
            account_id=R2_ACCOUNT_ID,
            access_key=R2_ACCESS_KEY_ID,
            secret_key=R2_SECRET_ACCESS_KEY,
            bucket=R2_BUCKET_NAME,
            key=R2_OBJECT_KEY,
        )

        # Step 2: Stream via FFmpeg (no disk I/O)
        stream_fal_to_r2(fal_url=FAL_VIDEO_URL, presigned_url=put_url)

        print("\n✅ Done — video is now available in R2:")
        print(f"   Bucket : {R2_BUCKET_NAME}")
        print(f"   Key    : {R2_OBJECT_KEY}")
        sys.exit(0)

    except RuntimeError as exc:
        print(f"\n❌ Error: {exc}", file=sys.stderr)
        sys.exit(1)
