"""
Video Generation Service
========================
Handles AI video generation via LTX Video 2.3 (fal.ai) — fast, high-quality
short-form vertical video for social media reels.

Primary Pipeline:
    LTX Video 2.3 (fal-ai/ltx-video)
    - image-to-video: product image directly → animated product reel
    - text-to-video:  prompt only (when no product image available)

    WHY LTX Video 2.3 fast:
    - ~30s generation (vs ~3–5 min for Kling 2.6 Pro)
    - Native 9:16 portrait output with direct product image conditioning
    - 8-step fast inference mode: quality/speed balance for social media
    - No Flux intermediate step needed — product image fed directly to LTX

Providers (priority order):
    1. LTX Video 2.3 via fal.ai   — primary (~30s, fast)
    2. Google Veo 2.0             — quality fallback (slow, expensive)
    3. Sample video               — free fallback for dev / CI
"""

import os
import asyncio
import logging
from typing import Optional

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Model Constants
# ─────────────────────────────────────────────────────────────────────────────

LTX_MODEL = "fal-ai/ltx-video"

# 9:16 portrait dimensions for LTX Video (must be multiples of 32)
# 432 × 768 = 0.5625 = 9/16 portrait aspect ratio ✓
LTX_WIDTH  = 432
LTX_HEIGHT = 768

# Fast inference: 8 steps takes ~30s and produces social-media-ready quality.
# Full quality: 40+ steps for ~3 min with marginal improvement for short-form.
LTX_INFERENCE_STEPS = 8

# LTX Video 2.3 frame limit: (num_frames - 1) must be divisible by 8.
# Cap at 257 frames (~10.3s at 25fps) for model stability.
LTX_MAX_FRAMES = 257

# Standard quality issues to suppress in LTX Video output
LTX_NEGATIVE_PROMPT = (
    "low quality, worst quality, deformed, distorted, disfigured, "
    "motion smear, motion artifacts, fused fingers, bad anatomy, weird hands, "
    "ugly, blurry, overexposed, watermark"
)


# ─────────────────────────────────────────────────────────────────────────────
# Duration → Frame Count Conversion
# ─────────────────────────────────────────────────────────────────────────────

def _duration_to_ltx_frames(seconds: int) -> int:
    """
    Map requested duration (seconds) to the nearest valid LTX num_frames.

    LTX Video requires (num_frames - 1) % 8 == 0.
    Preset mapping (25 fps):
        ≤ 5s  → 97 frames  (~4s)   fast-mode sweet spot
        ≤ 7s  → 129 frames (~5s)
        ≤ 10s → 193 frames (~8s)
        > 10s → 257 frames (~10s)  model maximum for stable output

    Args:
        seconds: Target clip length requested by the user

    Returns:
        num_frames value to pass to the LTX Video API
    """
    if seconds <= 5:  return 97    # ~4s — LTX fast mode sweet spot
    if seconds <= 7:  return 129   # ~5s
    if seconds <= 10: return 193   # ~8s
    return 257                     # ~10s — LTX stability ceiling


# ─────────────────────────────────────────────────────────────────────────────
# LTX Video 2.3 — Primary Generator
# ─────────────────────────────────────────────────────────────────────────────

async def generate_with_ltx(
    prompt: str,
    image_url: Optional[str] = None,
    duration: int = 5,
) -> str:
    """
    Generate a video clip using LTX Video 2.3 fast (fal-ai/ltx-video).

    Mode selection:
        With image_url  → image-to-video: LTX animates FROM the product photo,
                          preserving product identity while adding camera motion.
        Without image   → text-to-video: full scene generated from prompt alone.

    Optimal LTX prompt format (short + motion-first):
        Lead with subject + action, then camera, then environment.
        Keep under 350 chars — LTX responds better to concise, direct prompts.
        Camera instruction is CRITICAL: always include one explicit camera cue.
        Example:
            "A woman holds the product up to sunlight in a park.
             Camera slowly zooms in. Warm golden backlight."

    Args:
        prompt:    Scene description optimised for LTX Video (motion-first format,
                   200–350 chars ideal). Generated by Gemini in ai_service.py.
        image_url: Public/presigned product image URL to anchor the first frame.
                   Pass None to use text-to-video mode.
        duration:  Requested clip length in seconds — converted to num_frames.

    Returns:
        Public CDN URL (fal.media) of the generated video clip.

    Raises:
        RuntimeError: If fal.ai API call fails or response lacks a video URL.
    """
    try:
        import fal_client

        num_frames = _duration_to_ltx_frames(duration)
        mode = "image-to-video" if image_url else "text-to-video"

        arguments: dict = {
            "prompt":               prompt,
            "negative_prompt":      LTX_NEGATIVE_PROMPT,
            "height":               LTX_HEIGHT,
            "width":                LTX_WIDTH,
            "num_frames":           num_frames,
            # 8 steps = fast mode: ~30s generation, solid social-media quality
            "num_inference_steps":  LTX_INFERENCE_STEPS,
            "guidance_scale":       3.5,
        }

        if image_url:
            # Product image anchors the first frame so LTX preserves product
            # identity while animating the described camera movement and scene.
            arguments["image_url"] = image_url

        logger.info(
            f"[LTX] {mode} | frames={num_frames} (~{num_frames // 25}s) | "
            f"steps={LTX_INFERENCE_STEPS} | prompt={prompt[:70]}..."
        )

        def _run():
            result = fal_client.run(LTX_MODEL, arguments=arguments)
            # LTX Video response: {"video": {"url": "https://fal.media/...mp4"}}
            video = result.get("video") or {}
            url = video.get("url")
            if not url:
                raise RuntimeError(f"LTX returned no video URL. Response: {result}")
            return url

        loop = asyncio.get_running_loop()
        url = await loop.run_in_executor(None, _run)
        logger.info(f"[LTX] Done: {url}")
        return url

    except Exception as e:
        logger.error(f"[LTX] Generation failed: {e}")
        raise RuntimeError(f"LTX Video generation failed: {e}") from e


# ─────────────────────────────────────────────────────────────────────────────
# Public facade — entry point used by worker.py
# ─────────────────────────────────────────────────────────────────────────────

async def generate_video(
    prompt: str,
    image_url: Optional[str] = None,
    resolution: str = "720p",   # kept for API compatibility; LTX uses height/width internally
    duration: int = 5,
) -> str:
    """
    Generate a video using the best available provider (LTX → Veo → sample).

    Provider priority:
        1. LTX Video 2.3 via fal.ai   (primary: fast, ~30s per clip)
        2. Google Veo 2.0             (quality fallback: slow, expensive)
        3. Sample video               (dev / CI only: no AI required)

    Args:
        prompt:     Creative brief enriched with product metadata (from worker.py).
                    Should follow LTX prompt format: short, motion-first, 200–350 chars.
        image_url:  Product image URL — enables image-to-video mode in LTX.
        resolution: Ignored by LTX (format set by height/width). Kept for API compat.
        duration:   Clip length in seconds — passed to LTX frame calculation.

    Returns:
        Public CDN URL (fal.media) or R2 object key of the generated video.
    """
    fal_key       = os.getenv("FAL_KEY", "")
    veo_enabled   = os.getenv("VEO_ENABLED", "false").lower() == "true"
    google_ai_key = os.getenv("GOOGLE_AI_API_KEY", "")

    # ── Option 1: LTX Video 2.3 via fal.ai (primary — fast, ~30s)
    if fal_key:
        try:
            return await generate_with_ltx(prompt, image_url, duration)
        except Exception as e:
            logger.warning(f"[LTX] Primary generation failed, trying Veo: {e}")

    # ── Option 2: Google Veo 2.0 (best quality, slow / expensive)
    if veo_enabled and google_ai_key:
        try:
            return await _generate_with_veo(prompt)
        except Exception as e:
            logger.warning(f"[Veo] Fallback failed, using sample video: {e}")

    # ── Option 3: Sample video (free, development / CI only)
    logger.info("[Video] No AI provider available — using sample video placeholder")
    await asyncio.sleep(3)
    return "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"


# ─────────────────────────────────────────────────────────────────────────────
# Veo 2.0 — quality fallback (not the primary path)
# ─────────────────────────────────────────────────────────────────────────────

async def _generate_with_veo(prompt: str) -> str:
    """
    Generate video using Google Veo 2.0 (best quality but slow / expensive).

    Steps:
        1. Submit generation request (returns operation ID)
        2. Poll every 10s (max 5 min timeout)
        3. Download video from Google storage
        4. Upload to R2 for a permanent URL

    Args:
        prompt: Creative brief

    Returns:
        Public URL to the generated video (R2 or Google URI fallback)

    Raises:
        RuntimeError: If operation times out, download fails, or R2 upload fails
    """
    import time
    import uuid
    import requests
    import boto3
    from google import genai

    google_ai_key = os.getenv("GOOGLE_AI_API_KEY")
    r2_endpoint   = os.getenv("R2_ENDPOINT_URL")
    r2_key_id     = os.getenv("R2_ACCESS_KEY_ID")
    r2_secret     = os.getenv("R2_SECRET_ACCESS_KEY")
    r2_bucket     = os.getenv("R2_BUCKET_NAME")
    r2_public     = os.getenv("R2_PUBLIC_URL", "").rstrip("/")

    if not google_ai_key:
        raise RuntimeError("GOOGLE_AI_API_KEY not configured")

    try:
        client = genai.Client(api_key=google_ai_key)
        logger.info(f"[Veo] Starting generation: {prompt[:80]}...")

        def _generate_and_upload():
            operation = client.models.generate_videos(
                model="veo-2.0-generate-001",
                prompt=prompt,
                config={"number_of_videos": 1},
            )
            logger.info(f"[Veo] Submitted: {operation.name}")

            max_wait, waited = 300, 0
            while not operation.done and waited < max_wait:
                time.sleep(10)
                waited += 10
                operation = client.operations.get(operation.name)
                logger.info(f"[Veo] Generating… ({waited}s)")

            if not operation.done:
                raise RuntimeError(f"Veo timed out after {max_wait}s")
            if not (operation.response and operation.response.generated_videos):
                raise RuntimeError("Veo returned no videos")

            veo_uri = operation.response.generated_videos[0].video.uri
            download_url = (
                f"{veo_uri}&key={google_ai_key}"
                if "?" in veo_uri
                else f"{veo_uri}?key={google_ai_key}"
            )

            resp = requests.get(download_url, timeout=120)
            resp.raise_for_status()
            video_bytes = resp.content
            logger.info(f"[Veo] Downloaded {len(video_bytes):,} bytes")

            if not all([r2_endpoint, r2_key_id, r2_secret, r2_bucket]):
                logger.warning("[Veo] R2 not configured — returning Google URI")
                return veo_uri

            s3 = boto3.client(
                "s3",
                endpoint_url=r2_endpoint,
                aws_access_key_id=r2_key_id,
                aws_secret_access_key=r2_secret,
                region_name="auto",
            )
            object_key = f"videos/reels/veo/{uuid.uuid4().hex}.mp4"
            s3.put_object(
                Bucket=r2_bucket, Key=object_key,
                Body=video_bytes, ContentType="video/mp4",
            )
            logger.info(f"[Veo] Uploaded to R2: {object_key}")
            return (
                f"{r2_public}/{object_key}"
                if r2_public
                else f"{r2_endpoint.rstrip('/')}/{r2_bucket}/{object_key}"
            )

        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, _generate_and_upload)

    except Exception as e:
        logger.error(f"[Veo] Error: {e}")
        raise
